language: python
sudo: false
notifications:
  email: false
python:
- '2.7'
install:
- pip install -r server/python/requirements/dev.txt
script:
- flake8
- pytest
before_install:
- openssl aes-256-cbc -K $encrypted_9d6d1e1af018_key -iv $encrypted_9d6d1e1af018_iv
  -in .env.staging.enc -out .env.staging -d
- cp .env.staging .env
